### ISSUE TITLE
command in CTAN description is wrong

### ISSUE THREAD

**Issue by mbertucci47** [rf-latex/topcapt#1]
The CTAN [description](https://www.ctan.org/pkg/topcapt) says the command defined by the package is `\topcapt` but it should be `\topcaption`. Perhaps also the mentioned `caption` command could get a backslash.

**Comment by davidcarlisle** [comment]
so it does, thanks, I can't directly change it but I'll drop ctan an email.

**Comment by davidcarlisle** [comment]
ctan emailed

**Comment by manfredlotz** [comment]
@mbertucci47 Corrected on CTAN site.

**Comment by davidcarlisle** [comment]
@manfredlotz  thanks:-)
